[general]
import = ["~/.config/alacritty/tokyonight_night.toml"]

[font]
size = 10

normal = { family = "monospace", style = "Regular" }

[colors.cursor]
cursor = "#CD974C"
text = "#000000"

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Beam"

[window]
dynamic_padding = true

[window.padding]
x = 1
y = 1

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  # disable the default Alacritty binding so CTRL+SHIFT+C gets passed through
  { key = "C", mods = "Control|Shift", action = "ReceiveChar" },
  # alternative copy binding that always works
  { key = "C", mods = "Control|Alt", action = "Copy" },

  { key = "V", mods = "Control", action = "Paste" },
]
