"$schema" = "https://starship.rs/config-schema.json"

# I'm using $fill instaead of right_format, because right_format is not compatible with a multi-line prompt
right_format = ""

continuation_prompt = "[∙](bright-black) "
scan_timeout = 30
command_timeout = 500
add_newline = true
follow_symlinks = true

format = """\
$directory\
${custom.giticon}\
$git_branch\
${custom.wip}\
$git_commit\
$git_state\
$git_status\
$fill\

${custom.mise_env}\
$status\
$cmd_duration\
$line_break\

$jobs\
$battery\
$container\
$netns\
$character\
"""

[custom.giticon]
description = "Display icon for remote Git server"
command = """
    # Check if a remote tracking branch exists
    GIT_NO_REMOTE=$(git rev-list --count --right-only @{u}.. 2> /dev/null)

    if [[ -z "$GIT_NO_REMOTE" ]]; then
        GIT_REMOTE_SYMBOL=" "
    else
        GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
        if [[ "$GIT_REMOTE" =~ "github" ]]; then
            GIT_REMOTE_SYMBOL="" # nf-fa-github
        elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
            GIT_REMOTE_SYMBOL="" # nf-fa-gitlab
        elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
            GIT_REMOTE_SYMBOL="" # nf-fa-bitbucket
        elif [[ "$GIT_REMOTE" =~ "git" ]]; then
            GIT_REMOTE_SYMBOL="" # nf-fa-git_square
        else
            GIT_REMOTE_SYMBOL="󰊢 " # nf-md-git
        fi
    fi
    echo "$GIT_REMOTE_SYMBOL "
"""
require_repo = true
when = true
style = "bold purple"
format = "[$output ]($style)"

[custom.wip]
command = "echo \"wip \""
format = "[$output](yellow bold) "
when = "git log -1 --pretty=%B | grep -i \"wip\" >/dev/null"

[custom.mise_env]
description = "Display the current MISE_ENV"
command = "printf '%s' \"$MISE_ENV\""
when = "[ -n \"$MISE_ENV\" ]"
symbol = "󰭼 "
style = "#C75B7A"
format = "[$symbol$output]($style) "

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "
disabled = false
format = "[$symbol$percentage]($style) "

[[battery.display]]
threshold = 10
style = "red bold"

[character]
format = "$symbol "
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_visual_symbol = "[❮](bold yellow)"
vimcmd_replace_symbol = "[❮](bold purple)"
vimcmd_replace_one_symbol = "[❮](bold purple)"
disabled = false

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "#87875F"
show_milliseconds = false
disabled = false
show_notifications = false
min_time_to_notify = 45000

[container]
format = '[$symbol \[$name\]]($style) '
symbol = "⬢"
style = "red bold dimmed"
disabled = false

[directory]
truncation_length = 2
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true
format = "[$path]($style)[$read_only]($read_only_style) "
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
style = "#00AFFF bold"
disabled = false
read_only = " 󰌾"
read_only_style = "red"
truncation_symbol = "…"
home_symbol = "~"
use_os_path_sep = true

[fill]
symbol = '─'
style = '#333333'

[git_branch]
format = "[$branch(:$remote_branch)]($style) "
symbol = " "
style = "bold purple"
truncation_length = 24
truncation_symbol = "…"
only_attached = false
always_show_remote = false
ignore_branches = []
ignore_bare_repo = false
disabled = false

# [git_branch]
# only_attached = true
# style = "fg:green"
# format = "[$branch]($style) "

[git_commit]
commit_hash_length = 7
format = '[\($hash$tag\)]($style) '
style = "green bold"
only_detached = true
disabled = false
tag_symbol = " 🏷  "
tag_disabled = true
tag_max_candidates = 0

[git_state]
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "bold yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '
disabled = false

[git_status]
stashed = ''
untracked = '[?$count ](fg:cyan)'
deleted = '[-$count ](fg:red)'
modified = '[!$count ](fg:yellow)'
renamed = '[»$count ](fg:blue)'
staged = '[+$count ](fg:green)'
conflicted = '[  $count ](fg:red)'
diverged = '[󰃻 $count ](fg:red)'
ahead = '[⇡$count ](fg:cyan)'
behind = '[⇣$count ](fg:yellow)'
index_added = '[+$count ](fg:green)'
index_modified = '[~$count ](fg:green)'
index_deleted = '[-$count ](fg:red)'
index_typechanged = '[T$count ](fg:purple)'
worktree_modified = '[!$count ](fg:yellow)'
worktree_deleted = '[-$count ](fg:red)'
worktree_typechanged = '[T$count ](fg:yellow)'
# Three sections:
# upstream status + separator
# changes that `git commit` would include
# separator + everything else in the repo state.
format = """\
$ahead_behind[|](fg:#333333) \
$index_added$index_modified$renamed$index_deleted$index_typechanged\
[|](fg:#333333) $conflicted$worktree_modified$worktree_deleted$worktree_typechanged$untracked$stashed\
"""
use_git_executable = true

[jobs]
threshold = 1
symbol_threshold = 1
number_threshold = 2
format = "[$symbol$number]($style) "
symbol = "✦"
style = "bold blue"
disabled = false

[line_break]
disabled = false

[netns]
format = '[$symbol \[$name\]]($style) '
symbol = "🛜"
style = "blue bold dimmed"
disabled = false

[status]
format = '[\[$common_meaning$signal_name $int\]]($style) '
style = "bold red"
map_symbol = false
recognize_signal_code = true
disabled = false
