#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config mouse_follows_focus off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_zoom_persist on
yabai -m config window_topmost off
yabai -m config window_shadow off
yabai -m config window_animation_duration 0.0
yabai -m config window_animation_frame_rate 120
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 1.0

yabai -m config split_ratio 0.50
yabai -m config split_type auto
yabai -m config auto_balance off
yabai -m config top_padding 0
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 8
yabai -m config layout bsp
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# find app names with `yabai -m query --windows`
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^zoom\.us$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Snagit 2024$" manage=off
yabai -m rule --add app="^ColorSlurp$" manage=off
yabai -m rule --add subrole="^AXDialog$" manage=off
yabai -m rule --add app="^UTM$" manage=off
yabai -m rule --add app="^Bartender.*$" manage=off

echo "yabai configuration loaded.."
